import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { marked } from "marked";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const postsDir = path.join(__dirname, "..", "content", "posts");
const outputFile = path.join(__dirname, "..", "src", "data", "posts.js");

/**
 * Configure marked with GitHub Flavored Markdown (GFM) options
 */
marked.setOptions({
  breaks: true,           // Convert \n to <br>
  gfm: true,             // Enable GitHub Flavored Markdown
});

/**
 * Parse YAML-like front matter from markdown
 */
function parseFrontMatter(content) {
  const frontMatterRegex = /^---\n([\s\S]*?)\n---\n/;
  const match = content.match(frontMatterRegex);

  if (!match) {
    return { metadata: {}, content: content };
  }

  const frontMatter = match[1];
  const markdownContent = content.slice(match[0].length);

  const metadata = {};
  frontMatter.split("\n").forEach(line => {
    const [key, ...valueParts] = line.split(": ");
    if (key && valueParts.length > 0) {
      metadata[key.trim()] = valueParts.join(": ").trim();
    }
  });

  return { metadata, content: markdownContent };
}

/**
 * Generate posts.js by discovering and parsing all markdown files in content/posts/
 */
function generatePostsFile() {
  // Ensure directory exists
  if (!fs.existsSync(postsDir)) {
    console.error(`❌ Posts directory not found: ${postsDir}`);
    process.exit(1);
  }

  // Find all markdown files
  const files = fs.readdirSync(postsDir)
    .filter(f => f.endsWith(".md"))
    .sort();

  if (files.length === 0) {
    console.warn(`⚠️  No markdown files found in ${postsDir}`);
  }

  // Parse all markdown files
  const posts = files.map(file => {
    const filePath = path.join(postsDir, file);
    const fileContent = fs.readFileSync(filePath, "utf-8");
    const { metadata, content } = parseFrontMatter(fileContent);

    // Parse markdown to HTML
    const htmlContent = marked(content);

    return {
      title: metadata.title || "Untitled",
      date: metadata.date || new Date().toISOString().split("T")[0],
      slug: metadata.slug || file.replace(".md", ""),
      content: htmlContent,
    };
  });

  // Sort by date (newest first)
  posts.sort((a, b) => new Date(b.date) - new Date(a.date));


  // Generate the posts.js file
  const code = `/**
 * Blog posts - automatically generated from markdown files in content/posts/
 * 
 * This file is generated by scripts/build-posts.js
 * To add a new post, simply create a new .md file in content/posts/ with:
 * 
 * ---
 * title: Your Post Title
 * date: YYYY-MM-DD
 * slug: your-post-slug
 * ---
 * 
 * Your markdown content here...
 */

  export const posts = ${JSON.stringify(posts, null, 2)};
`;

  fs.writeFileSync(outputFile, code);
  console.log(`✓ Generated ${outputFile} from ${files.length} markdown file(s)`);
  console.log(`  Posts: ${posts.map(p => p.slug).join(", ") || "none"}`);
}

generatePostsFile();
